project_id = "jbnnmapqaoapsrednasd"

[functions.sync-klaviyo]
verify_jwt = false

[functions.generate-certificate]
verify_jwt = false

[functions.get-score-percentile]
verify_jwt = false

[functions.save-diagnostic-progress]
verify_jwt = false
